### YamlMime:PowershellCmdlet
summary: |-
  This cmdlet is available in on-premises Exchange and in the cloud-based service. Some parameters and settings may be exclusive to one environment or the other.

  Use the Get-AvailabilityConfig cmdlet to view information about the sharing of free/busy information between organizations:

  - In on-premises Exchange, the cmdlet returns the accounts that are trusted in the cross-forest sharing of free/busy information.
  - In Exchange Online, the cmdlet returns the tenant IDs of organizations that free/busy information is being shared with.

  For information about the parameter sets in the Syntax section below, see [Exchange cmdlet syntax](https://learn.microsoft.com/powershell/exchange/exchange-cmdlet-syntax).
module: ExchangePowerShell
notes: ""
inputs:
- name: <xref href="Input types" data-throw-if-not-resolved="False" />
  description: |-
    To see the input types that this cmdlet accepts, see [Cmdlet Input and Output Types](https://go.microsoft.com/fwlink/p/?LinkId=616387). If the Input Type field for a cmdlet is blank, the cmdlet doesn't accept input data.
outputs:
- name: <xref href="Output types" data-throw-if-not-resolved="False" />
  description: |-
    To see the return types, which are also known as output types, that this cmdlet accepts, see [Cmdlet Input and Output Types](https://go.microsoft.com/fwlink/p/?LinkId=616387). If the Output Type field is blank, the cmdlet doesn't return data.
syntaxes:
- >-
  Get-AvailabilityConfig [[-Identity] <OrganizationIdParameter>]

   [-DomainController <Fqdn>]

   [<CommonParameters>]
examples:
- title: Example 1
  code: |-
    Get-AvailabilityConfig
  description: |-
    In on-premises Exchange, this example returns the accounts that are trusted in the cross-forest shared of free/busy information.

    In Exchange Online, this examples returns the tenant IDs that free/busy information is being shared with.
  summary: ""
parameters:
- type: <xref href="Fqdn" data-throw-if-not-resolved="False" />
  name: DomainController
  description: |+
    This parameter is available only in on-premises Exchange.

    The DomainController parameter specifies the domain controller that's used by this cmdlet to read data from or write data to Active Directory. You identify the domain controller by its fully qualified domain name (FQDN). For example, dc01.contoso.com.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Exchange Server 2010
  - Exchange Server 2013
  - Exchange Server 2016
  - Exchange Server 2019
  parameterValueGroup: ""
- type: <xref href="OrganizationIdParameter" data-throw-if-not-resolved="False" />
  name: Identity
  description: |+
    The Identity parameter specifies the availability configuration that you want to view. You don't need to use this parameter, because there's only one availability configuration object named Availability Configuration in any organization.

  defaultValue: None
  pipelineInput: true
  position: "1"
  aliases: ""
  applicable:
  - Exchange Server 2010
  - Exchange Server 2013
  - Exchange Server 2016
  - Exchange Server 2019
  - Exchange Online
  parameterValueGroup: ""
applicable:
- Exchange Server 2010
- Exchange Server 2013
- Exchange Server 2016
- Exchange Server 2019
- Exchange Online
uid: ExchangePowerShell.Get-AvailabilityConfig
name: Get-AvailabilityConfig
description: |-
  You need to be assigned permissions before you can run this cmdlet. Although this topic lists all parameters for the cmdlet, you may not have access to some parameters if they're not included in the permissions assigned to you. To find the permissions required to run any cmdlet or parameter in your organization, see [Find the permissions required to run any Exchange cmdlet](https://learn.microsoft.com/powershell/exchange/find-exchange-cmdlet-permissions).
metadata:
  external help file: Microsoft.Exchange.CalendarsAndGroups-Help.xml
  online version: https://learn.microsoft.com/powershell/module/exchange/get-availabilityconfig
  applicable: Exchange Server 2010, Exchange Server 2013, Exchange Server 2016, Exchange Server 2019, Exchange Online
  title: Get-AvailabilityConfig
  schema: 2.0.0
  author: chrisda
  ms.author: chrisda
  ms.reviewer: ""
