### YamlMime:PowershellCmdlet
summary: |-
  Use the Get-CsBroadcastMeetingConfiguration cmdlet to retrieve the global (and only) broadcast meeting configuration for your organization.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href="None" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Rtc.Management.WritableConfig.Settings.UserServices.BroadcastMeetingConfiguration" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- >-
  Get-CsBroadcastMeetingConfiguration [-ExposeSDNConfigurationJsonBlob <Boolean>] [-Tenant <Guid>]

   [[-Identity] <XdsIdentity>] [-LocalStore] [<CommonParameters>]
- >-
  Get-CsBroadcastMeetingConfiguration [-ExposeSDNConfigurationJsonBlob <Boolean>] [-Tenant <Guid>]

   [-Filter <String>] [-LocalStore] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 --------------------------'
  code: |-
    Get-CsBroadcastMeetingConfiguration
  description: |-
    This example returns the tenant's global broadcast meeting configuration.
  summary: ""
parameters:
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: ExposeSDNConfigurationJsonBlob
  description: |+
    When set to true, the cmdlet will only return broadcast meeting configuration settings that relate to the Software Defined Network configuration.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Online
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Filter
  description: |+
    This parameter is reserved for internal Microsoft use.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Online
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  description: |+
    This parameter is reserved for internal Microsoft use.

  defaultValue: None
  position: "2"
  aliases: ""
  applicable:
  - Skype for Business Online
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: LocalStore
  description: |+
    Retrieves the information from the local replica of the Central Management store, rather than the Central Management store itself.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Online
  parameterValueGroup: ""
- type: <xref href="Guid" data-throw-if-not-resolved="False" />
  name: Tenant
  description: |+
    This parameter is reserved for internal Microsoft use.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Online
  parameterValueGroup: ""
applicable:
- Skype for Business Online
uid: SkypeForBusiness.Get-CsBroadcastMeetingConfiguration
name: Get-CsBroadcastMeetingConfiguration
description: |-
  Use the Get-CsBroadcastMeetingConfiguration cmdlet to retrieve the global (and only) broadcast meeting configuration for your organization.

  To return a list of all the Role-Based Access Control (RBAC) roles a cmdlet has been assigned to (including any custom RBAC roles you have created), run the following command:

  `Get-CsAdminRole | Where-Object {$_.Cmdlets -Match "\<DesiredCmdletName\>"}`
metadata:
  external help file: Microsoft.Rtc.Management.Hosted.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/get-csbroadcastmeetingconfiguration
  applicable: Skype for Business Online
  title: Get-CsBroadcastMeetingConfiguration
  schema: 2.0.0
  manager: bulenteg
  author: tomkau
  ms.author: tomkau
  ms.reviewer: ""
