### YamlMime:PowershellCmdlet
summary: |-
  Returns information about Skype for Business on Mac capabilities which have been enabled in your organization. This cmdlet was introduced in Skype for Business Server 2015 Cumulative Update 6 (December 2017).
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href="None" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="System.Object" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: New-CsPlatformServiceSettings
  href: https://learn.microsoft.com/powershell/module/skype/new-csplatformservicesettings?view=skype-ps
- text: Set-CsPlatformServiceSettings
  href: https://learn.microsoft.com/powershell/module/skype/set-csplatformservicesettings?view=skype-ps
- text: Remove-CsPlatformServiceSettings
  href: https://learn.microsoft.com/powershell/module/skype/remove-csplatformservicesettings?view=skype-ps
syntaxes:
- Get-CsPlatformServiceSettings [[-Identity] <XdsIdentity>] [-LocalStore] [<CommonParameters>]
- Get-CsPlatformServiceSettings [-Filter <String>] [-LocalStore] [<CommonParameters>]
examples:
- title: '-------------------------- EXAMPLE 1 --------------------------'
  code: |-
    PS C:\> Get-CsPlatformServiceSettings
  description: |-
    This example shows you which of the Skype for Business on Mac features are enabled in your organization.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Filter
  description: |+
    Enables you to use wildcard characters in order to return one or more Platform Service Settings configurations.
    For example, to return all of the Platform Service Settings configurations with the word Test in their names use this syntax:

    -Filter "\*Test*"

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  description: |+
    Indicates the Identity of the Platform Service Settings to be returned.

  defaultValue: None
  position: "1"
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: LocalStore
  description: |+
    Retrieves the Platform Service Settings configuration data from the local replica of the Central Management store rather than from the Central Management store itself.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.Get-CsPlatformServiceSettings
name: Get-CsPlatformServiceSettings
description: |-
  Skype for Business Server 2015 Cumulative Update 6 introduces new features for Skype for Business on Mac users like support for E-911 calls, send files in peer-to-peer chats, block external access by policy and more.

  The `Get-CsPlatformServiceSettings` cmdlet shows you which of these features are enabled.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/get-csplatformservicesettings
  applicable: Skype for Business Server 2015, Skype for Business Server 2019
  title: Get-CsPlatformServiceSettings
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
