### YamlMime:PowershellCmdlet
summary: |-
  Use the Get-CsOnlineApplicationInstanceAssociation cmdlet to get information about the associations setup in your organization.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
  description: |-
    The Get-CsOnlineApplicationInstanceAssociation cmdlet accepts a string as the Identity parameter.
outputs:
- name: <xref href="Microsoft.Rtc.Management.Hosted.Online.Models.ApplicationInstanceAssociation" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Get-CsOnlineApplicationInstanceAssociationStatus
  href: Get-CsOnlineApplicationInstanceAssociationStatus.yml
- text: New-CsOnlineApplicationInstanceAssociation
  href: New-CsOnlineApplicationInstanceAssociation.yml
- text: Remove-CsOnlineApplicationInstanceAssociation
  href: Remove-CsOnlineApplicationInstanceAssociation.yml
syntaxes:
- Get-CsOnlineApplicationInstanceAssociation -Identity <String> [-Tenant <Guid>] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 --------------------------'
  code: |-
    Get-CsOnlineApplicationInstanceAssociation -Identity "f7a821dc-2d69-5ae8-8525-bcb4a4556093"
  description: |-
    This example gets the association object for the application instance that has the identity of f7a821dc-2d69-5ae8-8525-bcb4a4556093.
  summary: ""
parameters:
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Identity
  isRequired: true
  description: |+
    The identity for the application instance whose association is to be retrieved.

  defaultValue: None
  pipelineInput: true
  position: "0"
  aliases: ""
  applicable:
  - Skype for Business Online
  parameterValueGroup: ""
- type: <xref href="System.Guid" data-throw-if-not-resolved="False" />
  name: Tenant
  description: ""
  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Online
  parameterValueGroup: ""
applicable:
- Skype for Business Online
uid: SkypeForBusiness.Get-CsOnlineApplicationInstanceAssociation
name: Get-CsOnlineApplicationInstanceAssociation
description: |-
  Use the Get-CsOnlineApplicationInstanceAssociation cmdlet to get information about the associations setup between online application instances and the application configurations, like auto attendants and call queues.
metadata:
  external help file: Microsoft.Rtc.Management.Hosted.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/get-csonlineapplicationinstanceassociation
  applicable: Skype for Business Online
  title: Get-CsOnlineApplicationInstanceAssociation
  schema: 2.0.0
  manager: bulenteg
  author: tomkau
  ms.author: tomkau
  ms.reviewer: ""
