### YamlMime:PowershellCmdlet
summary: |-
  TeamsGuestMessagingConfiguration determines the messaging settings for the guest users.  This cmdlet returns your organization's current settings.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href="None" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="System.Object" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- >-
  Get-CsTeamsGuestMessagingConfiguration [-Tenant <Guid>] [[-Identity] <XdsIdentity>] [-LocalStore]

   [<CommonParameters>]
- >-
  Get-CsTeamsGuestMessagingConfiguration [-Tenant <Guid>] [-Filter <String>] [-LocalStore]

   [<CommonParameters>]
examples:
- title: Example 1
  code: |-
    Get-CsTeamsGuestMessagingConfiguration
  description: |-
    The command shown in Example 1 returns teams guest messaging configuration information for the current tenant
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Filter
  description: |+
    Enables you to use wildcard characters in order to return a collection of tenant guest messaging configuration settings.
    Because each tenant is limited to a single, global collection of guest messaging configuration settings there is no need to use the Filter parameter.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  description: |+
    Specifies the collection of tenant guest messaging configuration settings to be returned.
    Because each tenant is limited to a single, global collection of guest messaging settings there is no need include this parameter when calling the cmdlet.
    If you do choose to use the Identity parameter you must also include the Tenant parameter.

  defaultValue: None
  position: "1"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: LocalStore
  description: |+
    This parameter is not used with Skype for Business Online.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Guid" data-throw-if-not-resolved="False" />
  name: Tenant
  description: |+
    This parameter is reserved for internal Microsoft use.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
applicable:
- Skype for Business Online
uid: SkypeForBusiness.Get-CsTeamsGuestMessagingConfiguration
name: Get-CsTeamsGuestMessagingConfiguration
description: |-
  TeamsGuestMessagingConfiguration determines the messaging settings for the guest users.
metadata:
  external help file: Microsoft.Rtc.Management.Hosted.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/get-csteamsguestmessagingconfiguration
  applicable: Skype for Business Online
  title: Get-CsTeamsGuestMessagingConfiguration
  schema: 2.0.0
  manager: bulenteg
  author: tomkau
  ms.author: tomkau
  ms.reviewer: ""
