### YamlMime:PowershellCmdlet
summary: |-
  Creates an application instance in Microsoft Entra ID.
module: SkypeForBusiness
notes: ""
links:
- text: Get-CsOnlineApplicationInstance
  href: Get-CsOnlineApplicationInstance.yml
- text: Set-CsOnlineApplicationInstance
  href: Set-CsOnlineApplicationInstance.yml
- text: Find-CsOnlineApplicationInstance
  href: Find-CsOnlineApplicationInstance.yml
- text: Sync-CsOnlineApplicationInstance
  href: Sync-CsOnlineApplicationInstance.yml
syntaxes:
- New-CsOnlineApplicationInstance [-UserPrincipalName] <string> [[-ApplicationId] <guid>] [[-DisplayName] <string>] [-Force] [-WhatIf] [-Confirm] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 --------------------------'
  code: |-
    New-CsOnlineApplicationInstance -UserPrincipalName appinstance01@contoso.com -ApplicationId ce933385-9390-45d1-9512-c8d228074e07 -DisplayName "AppInstance01"
  description: |-
    This example creates a new application instance for an Auto Attendant with UserPrincipalName "appinstance01@contoso.com", ApplicationId "ce933385-9390-45d1-9512-c8d228074e07", DisplayName "AppInstance01" for the tenant.
  summary: ""
parameters:
- type: <xref href="System.Guid" data-throw-if-not-resolved="False" />
  name: ApplicationId
  description: |+
    The application ID. The Microsoft application Auto Attendant has the ApplicationId ce933385-9390-45d1-9512-c8d228074e07 and the Microsoft application Call Queue has the ApplicationId 11cd3e2e-fccb-42ad-ad00-878b93575e07. Third-party applications available in a tenant will use other ApplicationId's.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Microsoft Teams
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: "False"
  position: Named
  aliases: cf
  applicable:
  - Microsoft Teams
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: DisplayName
  description: |+
    The display name.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Microsoft Teams
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    This switch specifies whether to suppress warning and confirmation messages. It can be useful in scripting to suppress interactive prompts. If it isn't provided in the command, you're prompted for administrative input if required.

  defaultValue: "False"
  position: Named
  aliases: ""
  applicable:
  - Microsoft Teams
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: UserPrincipalName
  isRequired: true
  description: |+
    The user principal name. It will be used as the SIP URI too. The user principal name should have an online domain.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Microsoft Teams
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: "False"
  position: Named
  aliases: wi
  applicable:
  - Microsoft Teams
  parameterValueGroup: ""
applicable:
- Microsoft Teams
uid: SkypeForBusiness.New-CsOnlineApplicationInstance
name: New-CsOnlineApplicationInstance
description: |-
  This cmdlet is used to create an application instance in Microsoft Entra ID. This same cmdlet is also run when creating a new resource account using Teams Admin Center.
metadata:
  external help file: Microsoft.Rtc.Management.Hosted.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/new-csonlineapplicationinstance
  applicable: Microsoft Teams
  title: New-CsOnlineApplicationInstance
  schema: 2.0.0
  manager: bulenteg
  author: jenstrier
  ms.author: serdars
  ms.reviewer: ""
