### YamlMime:PowershellCmdlet
summary: |-
  Use the `New-CsVideoTrunkConfiguration` to create a new video trunk configuration containing settings to manage a video Session Initiation Protocol (SIP) trunk between the Video Interop Server (VIS) and a Video Gateway.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    None.
    The `New-CsVideoTrunkConfiguration` cmdlet does not accept pipelined input.
outputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    The `New-CsVideoTrunkConfiguration` cmdlet creates new instances of the Microsoft.Rtc.Management.WritableConfig.Settings.VideoTrunkConfiguration object.
links:
- text: Get-CsVideoTrunkConfiguration
  href: Get-CsVideoTrunkConfiguration.yml
- text: Set-CsVideoTrunkConfiguration
  href: Set-CsVideoTrunkConfiguration.yml
- text: Remove-CsVideoTrunkConfiguration
  href: Remove-CsVideoTrunkConfiguration.yml
syntaxes:
- >-
  New-CsVideoTrunkConfiguration [-Identity] <XdsIdentity> [-Confirm]

   [-EnableMediaEncryptionForSipOverTls <Boolean>] [-EnableSessionTimer <Boolean>] [-Force]

   [-ForwardErrorCorrectionType <String>] [-GatewaySendsRtcpForActiveCalls <Boolean>]

   [-GatewaySendsRtcpForCallsOnHold <Boolean>] [-InMemory] [-WhatIf] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 --------------------------'
  code: |-
    New-CsVideoTrunkConfiguration -Identity "site:Redmond" -EnableSessionTimer $True
  description: |-
    This example creates a new collection of video trunk configuration settings that are assigned to the Redmond site.
    Session timers are enabled on the new configuration by setting the EnableSessionTimer parameter to True ($True).
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: EnableMediaEncryptionForSipOverTls
  description: |+
    When set to True ($True) it is expected that the Video Gateway or third party video teleconferencing system (VTC) uses TLS to protect SIP signaling and uses SRTP to protect the media traffic.
    The default value is True ($True).

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: EnableSessionTimer
  description: |+
    Specifies whether the session timer is enabled.
    Session timers are used to determine whether a particular session is still active.
    The default is false ($False).

    Note that even if this parameter is set to False, session timers can be applicable if the remote connection has session timer enabled.
    In such a case, the Video Interop Server will reply to session timer probes from the remote entity.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Suppresses the display of any non-fatal error messages and completes the cmdlet operation.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ForwardErrorCorrectionType
  description: |+
    Specifies the type of Forward Error Correction (FEC) to be used between the Video Interop Server (VIS) and a Video Gateway.
    The valid settings are:

    None: Turns off FEC between the VIS and the Video Gateway.

    Cisco: Enables FEC compatible with Cisco Video Gateways, such as Cisco Unified Communications Manager (CUCM).

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: GatewaySendsRtcpForActiveCalls
  description: |+
    When set to True ($True) it is expected that the Video Gateway or third party video teleconferencing system (VTC) sends RTCP for calls that are enabled for media sending from the Video Gateway or VTC.
    The default value is True ($True).

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: GatewaySendsRtcpForCallsOnHold
  description: |+
    When set to True ($True) it is expected that the Video Gateway or third party video teleconferencing system (VTC) sends RTCP for calls that are disabled for media sending from the Video Gateway or VTC.
    The default value is False ($False).

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  isRequired: true
  description: |+
    The Identity parameter specifies the unique identifier for the new collection of video trunk configuration settings.
    New collections can be created at either the site scope or the service scope (for the Video Gateway service only).

    For example, this syntax creates a new collection of settings assigned to the Redmond site: `-Identity "site:Redmond"`.
    And this syntax creates a new collection assigned to the Video Gateway "video-pbx-001.litwareinc.com": `-Identity "service:VideoGateway:video-pbx-001.litwareinc.com"`

  defaultValue: None
  position: "2"
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: InMemory
  description: |+
    Creates an object reference without actually committing the object as a permanent change.
    If you assign the output of this cmdlet called with this parameter to a variable, you can make changes to the properties of the object reference and then commit those changes by passing that object reference to the `Set-CsVideoTrunkConfiguration` cmdlet.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Describes what would happen if you executed the command without actually executing the command.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.New-CsVideoTrunkConfiguration
name: New-CsVideoTrunkConfiguration
description: |-
  The Video Interop Server in Skype for Business Server enables you to incorporate 3rd party video teleconferencing systems (VTCs) into your Skype for Business Server infrastructure.
  The Video Interop Server is a Skype service that runs on a standalone pool and cannot be co-located on an FE pool.

  To enable the Video Interop Server, you must use Topology Builder to define at least one VIS instance.
  Each VIS instance will typically be associated with one or more Video Gateways.
  Video Gateways route traffic between internal and third party video devices such as an internal Skype endpoint receiving video from a third party PBX supporting 3rd party video teleconferencing systems (VTCs).
  The Video Gateway and a Video Interop Server (VIS) use a Session Initiation Protocol (SIP) trunk to connect video calls between third party VTCs and internal endpoints.

  Video Trunks settings can be managed by using the CsVideoTrunkConfiguration cmdlets.
  These settings are used to manage the following Video Trunk characteristics.

  RTCP for active calls

  RTCP for calls on hold

  Secure Real-time Transport Protocol (SRTP) use when Transport Layer Security (TLS) is used for the SIP signaling

  Session timers usage on the Video Interop Server (VIS) for dialogs associated with a Video Trunk

  By default, Skype for Business Server ships with a single, global collection of Video Trunk configuration settings.
  However, administrators can use the `New-CsVideoTrunkConfiguration` cmdlet to create additional settings at the site or the service scope (for the Video Gateway service only).
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/new-csvideotrunkconfiguration
  applicable: Skype for Business Server 2015, Skype for Business Server 2019
  title: New-CsVideoTrunkConfiguration
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
