### YamlMime:PowershellCmdlet
summary: |-
  Use the Remove-CsOnlineApplicationInstanceAssociation cmdlet to remove the association between an application instance and the associated application configuration.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href="System.String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  description: |-
    The Remove-CsOnlineApplicationInstanceAssociation cmdlet accepts a string array as the Identities parameter.
outputs:
- name: <xref href="Microsoft.Rtc.Management.Hosted.Online.Models.AssociationOperationOutput" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Get-CsOnlineApplicationInstanceAssociation
  href: Get-CsOnlineApplicationInstanceAssociation.yml
- text: Get-CsOnlineApplicationInstanceAssociationStatus
  href: Get-CsOnlineApplicationInstanceAssociationStatus.yml
- text: New-CsOnlineApplicationInstanceAssociation
  href: New-CsOnlineApplicationInstanceAssociation.yml
syntaxes:
- Remove-CsOnlineApplicationInstanceAssociation -Identities <String[]> [-Tenant <Guid>] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 --------------------------'
  code: |-
    Remove-CsOnlineApplicationInstanceAssociation -Identities "f7a821dc-2d69-5ae8-8525-bcb4a4556093"
  description: |-
    This example removes the configuration association for the application instance that has the identity of "f7a821dc-2d69-5ae8-8525-bcb4a4556093".
  summary: ""
parameters:
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Identities
  isRequired: true
  description: |+
    The identities for the application instances whose configuration associations are to be removed.

  defaultValue: None
  pipelineInput: true
  position: "0"
  aliases: ""
  applicable:
  - Skype for Business Online
  parameterValueGroup: ""
- type: <xref href="System.Guid" data-throw-if-not-resolved="False" />
  name: Tenant
  description: ""
  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Online
  parameterValueGroup: ""
applicable:
- Skype for Business Online
uid: SkypeForBusiness.Remove-CsOnlineApplicationInstanceAssociation
name: Remove-CsOnlineApplicationInstanceAssociation
description: |-
  Use the Remove-CsOnlineApplicationInstanceAssociation cmdlet to remove the association between an application instance and the associated application configuration.

  This is useful when you want to associate this application instance with another application configuration for handling incoming calls.
metadata:
  external help file: Microsoft.Rtc.Management.Hosted.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/remove-csonlineapplicationinstanceassociation
  applicable: Skype for Business Online
  title: Remove-CsOnlineApplicationInstanceAssociation
  schema: 2.0.0
  manager: bulenteg
  author: tomkau
  ms.author: tomkau
  ms.reviewer: ""
