### YamlMime:PowershellCmdlet
summary: |-
  The TeamsClientConfiguration allows IT admins to control the settings that can be accessed via Teams clients across their organization.  This configuration includes settings like which third party cloud storage your organization allows, whether or not guest users can access the teams client, and how Surface Hub devices can interact with Skype for Business meetings.  The parameter descriptions below describe what settings are managed by this configuration and how they are enforced.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href="System.Management.Automation.PSObject" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="System.Object" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- >-
  Set-CsTeamsClientConfiguration [-Tenant <System.Guid>] [-AllowEmailIntoChannel <Boolean>]

   [-RestrictedSenderList <String>] [-AllowDropBox <Boolean>] [-AllowEgnyte <Boolean>] [-AllowBox <Boolean>] [-AllowGoogleDrive <Boolean>] [-AllowRoleBasedChatPermissions <Boolean>]

   [-AllowShareFile <Boolean>] [-AllowOrganizationTab <Boolean>] [-AllowSkypeBusinessInterop <Boolean>]

   [-AllowTBotProactiveMessaging <Boolean>] [-ContentPin <String>] [-AllowResourceAccountSendMessage <Boolean>]

   [-ResourceAccountContentAccess <String>] [-AllowGuestUser <Boolean>]

   [-AllowScopedPeopleSearchandAccess <Boolean>] [[-Identity] <XdsIdentity>] [-Force] [-WhatIf] [-Confirm] 

   [<CommonParameters>]
- >-
  Set-CsTeamsClientConfiguration [-Tenant <System.Guid>] [-AllowEmailIntoChannel <Boolean>]

   [-RestrictedSenderList <String>] [-AllowDropBox <Boolean>] [-AllowEgnyte <Boolean>] [-AllowBox <Boolean>] [-AllowGoogleDrive <Boolean>] [-AllowRoleBasedChatPermissions <Boolean>]

   [-AllowShareFile <Boolean>] [-AllowOrganizationTab <Boolean>] [-AllowSkypeBusinessInterop <Boolean>]

   [-AllowTBotProactiveMessaging <Boolean>] [-ContentPin <String>] [-AllowResourceAccountSendMessage <Boolean>]

   [-ResourceAccountContentAccess <String>] [-AllowGuestUser <Boolean>]

   [-AllowScopedPeopleSearchandAccess <Boolean>] [-Instance <PSObject>] [-Force] [-WhatIf] [-Confirm] 

   [<CommonParameters>]
examples:
- title: Example 1
  code: |-
    PS C:\> Set-CsTeamsClientConfiguration -Identity Global -AllowDropBox $false
  description: |-
    In this example, the client configuration effective for the organization (Global) is being updated to disable the use of DropBox in the organization.  All other settings in the configuration remain the same.
  summary: ""
parameters:
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: AllowBox
  description: |+
    Designates whether users are able to leverage Box as a third party storage solution in Microsoft Teams.  If $true, users will be able to add Box in the client and interact with the files stored there.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: AllowDropBox
  description: |+
    Designates whether users are able to leverage DropBox as a third party storage solution in Microsoft Teams.  If $true, users will be able to add DropBox in the client and interact with the files stored there.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: AllowEgnyte
  description: |+
    Designates whether users are able to leverage Egnyte as a third party storage solution in Microsoft Teams.  If $true, users will be able to add Egnyte in the client and interact with the files stored there.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: AllowEmailIntoChannel
  description: |+
    When set to $true, mail hooks are enabled, and users can post messages to a channel by sending an email to the email address of Teams channel.

    To find the email address for a channel, click the More options menu for the channel and then select Get email address. 

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: AllowGoogleDrive
  description: |+
    Designates whether users are able to leverage GoogleDrive as a third party storage solution in Microsoft Teams.  If $true, users will be able to add Google Drive in the client and interact with the files stored there.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: AllowGuestUser
  description: |+
    Designates whether or not guest users in your organization will have access to the Teams client.  If $true, guests in your tenant will be able to access the Teams client.  Note that this setting has a core dependency on Guest Access being enabled in your Office 365 tenant.  For more information on this topic, read Authorize Guest Access in Microsoft Teams: https://learn.microsoft.com/microsoftteams/teams-dependencies

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: AllowOrganizationTab
  description: |+
    When set to $true, users will be able to see the organizational chart icon other users' contact cards, and when clicked, this icon will display the detailed organizational chart.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: AllowResourceAccountSendMessage
  description: |+
    Surface Hub uses a device account to provide email and collaboration services (IM, video, voice). This device account is used as the originating identity (the "from" party) when sending email, IM, and placing calls. As this account is not coming from an individual, identifiable user, it is deemed "anonymous" because it originated from the Surface Hub's device account. If set to $true, these device accounts will be able to send chat messages in Skype for Business Online (does not apply to Microsoft Teams).

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: AllowRoleBasedChatPermissions
  description: |+
    When set to True, Supervised Chat is enabled for the tenant.

  defaultValue: "False"
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: AllowScopedPeopleSearchandAccess
  description: |+
    If set to $true, the Exchange address book policy (ABP) will be used to provide customized view of the global address book for each user.  This is only a virtual separation and not a legal separation.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: AllowShareFile
  description: |+
    Designates whether users are able to leverage Citrix ShareFile as a third party storage solution in Microsoft Teams.  If $true, users will be able to add Citrix ShareFile in the client and interact with the files stored there.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: AllowSkypeBusinessInterop
  description: |+
    When set to $true, Teams conversations automatically show up in Skype for Business for users that aren't enabled for Teams. 

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: AllowTBotProactiveMessaging
  description: |+
    Deprecated, do not use.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: None
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ContentPin
  description: |+
    This setting applies only to Skype for Business Online (not Microsoft Teams) and defines whether the user must provide a secondary form of authentication to access the meeting content *from a resource device account*.  Meeting content is defined as files that are shared to the "Content Bin" - files that have been attached to the meeting.

    Possible Values: NotRequired, RequiredOutsideScheduleMeeting, AlwaysRequired .  Default Value: RequiredOutsideScheduleMeeting

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Bypass any verification checks and non-fatal errors.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  description: |+
    The only valid input is Global - the tenant wide configuration.

  defaultValue: None
  position: "1"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="PSObject" data-throw-if-not-resolved="False" />
  name: Instance
  description: |+
    You can use this to pass the results from Get-CsTeamsClientConfiguration into the Set-CsTeamsClientConfiguration rather than specifying the "-Identity Global" parameter.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ResourceAccountContentAccess
  description: |+
    Require a secondary form of authentication to access meeting content.

    Possible values: NoAccess, PartialAccess and FullAccess

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: RestrictedSenderList
  description: |+
    Senders domains can be further restricted to ensure that only allowed SMTP domains can send emails to the Teams channels.  This is a semicolon-separated string of the domains you'd like to *allow* to send emails to Teams channels.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.Guid" data-throw-if-not-resolved="False" />
  name: Tenant
  description: |+
    Internal Microsoft use only.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    The WhatIf switch does not work with this cmdlet.

  defaultValue: None
  position: Named
  aliases: wi
  parameterValueGroup: ""
applicable:
- Skype for Business Online
uid: SkypeForBusiness.Set-CsTeamsClientConfiguration
name: Set-CsTeamsClientConfiguration
description: |-
  The TeamsClientConfiguration allows IT admins to control the settings that can be accessed via Teams clients across their organization.  This configuration includes settings like which third party cloud storage your organization allows, whether or not guest users can access the teams client, and whether or not meeting room devices running teams are can display content from user accounts.  The parameter descriptions below describe what settings are managed by this configuration and how they are enforced. 

  An organization can have only one effective Teams Client Configuration - these settings will apply across the entire organization for the particular features they control.  

  Note that three of these settings (ContentPin, ResourceAccountContentAccess, and AllowResourceAccountSendMessage) control resource account behavior for Surface Hub devices attending Skype for Business meetings, and are not used in Microsoft Teams.
metadata:
  external help file: Microsoft.Rtc.Management.Hosted.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/set-csteamsclientconfiguration
  applicable: Skype for Business Online
  Module Name: Skype for Business Online
  title: Set-CsTeamsClientConfiguration
  schema: 2.0.0
  manager: bulenteg
  author: tomkau
  ms.author: tomkau
  ms.reviewer: ""
