### YamlMime:PowershellCmdlet
summary: |-
  Modifies the Skype for Business on Mac capabilities in your organization. This cmdlet was introduced in Skype for Business Server 2015 Cumulative Update 6 (December 2017).
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href="System.Management.Automation.PSObject" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="System.Object" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: New-CsPlatformServiceSettings
  href: https://learn.microsoft.com/powershell/module/skype/new-csplatformservicesettings?view=skype-ps
- text: Get-CsPlatformServiceSettings
  href: https://learn.microsoft.com/powershell/module/skype/get-csplatformservicesettings?view=skype-ps
- text: Remove-CsPlatformServiceSettings
  href: https://learn.microsoft.com/powershell/module/skype/remove-csplatformservicesettings?view=skype-ps
syntaxes:
- >-
  Set-CsPlatformServiceSettings [-EnableDelegateManagement <Boolean>] [-EnableExternalAccessCheck <Boolean>]

   [-EnablePushNotifications <Boolean>] [-UseLegacyPushNotifications <Boolean>] [-EnableE911 <Boolean>]

   [-EnableFileTransfer <Boolean>] [-EnableCORS <Boolean>] [-EnableUcwaScopeCheck <Boolean>]

   [-MaxRegistrationsPerPublicApplication <Int32>] [[-Identity] <XdsIdentity>] [-Force] [-WhatIf] [-Confirm]

   [<CommonParameters>]
- >-
  Set-CsPlatformServiceSettings [-EnableDelegateManagement <Boolean>] [-EnableExternalAccessCheck <Boolean>]

   [-EnablePushNotifications <Boolean>] [-UseLegacyPushNotifications <Boolean>] [-EnableE911 <Boolean>]

   [-EnableFileTransfer <Boolean>] [-EnableCORS <Boolean>] [-EnableUcwaScopeCheck <Boolean>]

   [-MaxRegistrationsPerPublicApplication <Int32>] [-Instance <PSObject>] [-Force] [-WhatIf] [-Confirm]

   [<CommonParameters>]
examples:
- title: '-------------------------- EXAMPLE 1 --------------------------'
  code: |-
    PS C:\> Set-CsPlatformServiceSettings -EnableDelegateManagement $False -EnableExternalAccessCheck $True -EnableE911 $False -EnableFil
    eTransfer $True
  description: |-
    This example modifies some parameters for global platform service settings.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: EnableCORS
  description: |+
    This parameter is reserved for Microsoft internal use only.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: EnableDelegateManagement
  description: |+
    Enables the ability to manage delegates from the Skype for Business on Mac client.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: EnableE911
  description: |+
    Allows Skype for Business on Mac users to call 911.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: EnableExternalAccessCheck
  description: |+
    Enables administrators to use external access policies to block external access to Skype for Business on Mac users. 

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: EnableFileTransfer
  description: |+
    Enables Skype for Business on Mac users send files in peer-to-peer chats.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: EnablePushNotifications
  description: |+
    Enables Skype for Business on Mac clients to use push notifications.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: EnableUcwaScopeCheck
  description: |+
    This parameter is reserved for Microsoft internal use only.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Suppresses any confirmation prompts that would otherwise be displayed before testing.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  description: |+
    Indicates the Identity of the Platform Service Settings to be modified.

  defaultValue: None
  position: "1"
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="PSObject" data-throw-if-not-resolved="False" />
  name: Instance
  description: |+
    Allows you to pass a reference to an object to the cmdlet rather than set individual parameter values. You can retrieve this object reference by calling the Get-CsPlatformServiceSettings cmdlet.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: MaxRegistrationsPerPublicApplication
  description: |+
    This parameter is reserved for Microsoft internal use only.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: UseLegacyPushNotifications
  description: |+
    This parameter is reserved for Microsoft internal use only.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.Set-CsPlatformServiceSettings
name: Set-CsPlatformServiceSettings
description: |-
  Skype for Business Server 2015 Cumulative Update 6 introduces new features for Skype for Business on Mac users like support for E-911 calls, send files in peer-to-peer chats, block external access by policy and more.

  The `Set-CsPlatformServiceSettings` cmdlet gives you control to enable or disable these features.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/set-csplatformservicesettings
  applicable: Skype for Business Server 2015, Skype for Business Server 2019
  title: Set-CsPlatformServiceSettings
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
