### YamlMime:PowershellCmdlet
summary: |-
  Manages federation configuration settings for your Skype for Business Online tenants.
  These settings are used to determine which domains (if any) your users are allowed to communicate with.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    The `Set-CsTenantFederationConfiguration` cmdlet accepts pipelined instances of the Microsoft.Rtc.Management.WritableConfig.Settings.Edge.TenantFederationSettings object.
outputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    None.
    Instead, the `Set-CsTenantFederationConfiguration` cmdlet modifies existing instances of the Microsoft.Rtc.Management.WritableConfig.Settings.Edge.TenantFederationSettings object.
links:
- text: Get-CsTenantFederationConfiguration
  href: Get-CsTenantFederationConfiguration.yml
- text: Get-CsTenantPublicProvider
  href: Get-CsTenantPublicProvider.yml
syntaxes:
- >-
  Set-CsTenantFederationConfiguration [-Tenant <Guid>] [-AllowedDomains <IAllowedDomainsChoice>]

   [-BlockedDomains <List>] [-AllowFederatedUsers <Boolean>] [-AllowPublicUsers <Boolean>] [-AllowTeamsConsumer <Boolean>] [-AllowTeamsConsumerInbound <Boolean>]

   [-TreatDiscoveredPartnersAsUnverified <Boolean>] [-SharedSipAddressSpace <Boolean>]

   [-AllowedDomainsAsAList <List>] [[-Identity] <XdsIdentity>] [-Force] [-WhatIf] [-Confirm] [<CommonParameters>]
- >-
  Set-CsTenantFederationConfiguration [-Tenant <Guid>] [-AllowedDomains <IAllowedDomainsChoice>]

   [-BlockedDomains <List>] [-AllowFederatedUsers <Boolean>] [-AllowPublicUsers <Boolean>]

   [-TreatDiscoveredPartnersAsUnverified <Boolean>] [-SharedSipAddressSpace <Boolean>]

   [-AllowedDomainsAsAList <List>] [-Instance <PSObject>] [-Force] [-WhatIf] [-Confirm] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 --------------------------'
  code: |-
    Set-CsTenantFederationConfiguration -AllowPublicUsers $False
  description: |-
    The command shown in Example 1 disables communication with public providers for the current tenant.
  summary: ""
- title: '-------------------------- Example 2 --------------------------'
  code: |-
    $x = New-CsEdgeDomainPattern -Domain "fabrikam.com"

    Set-CsTenantFederationConfiguration -BlockedDomains @{Replace=$x}
  description: |-
    In Example 2, the domain fabrikam.com is assigned as the only domain on the blocked domains list for current tenant.
    To do this, the first command in the example uses the `New-CsEdgeDomainPattern` cmdlet to create a new domain object for fabrikam.com.
    This domain object is stored in a variable named $x.

    The second command in the example then uses the `Set-CsTenantFederationConfiguration` cmdlet to update the blocked domains list.
    Using the Replace method ensures that the existing blocked domains list will be replaced by the new list: a list that contains only the domain fabrikam.com.
  summary: ""
- title: '-------------------------- Example 3 --------------------------'
  code: |-
    $x = New-CsEdgeDomainPattern -Domain "fabrikam.com"

    Set-CsTenantFederationConfiguration -BlockedDomains @{Remove=$x}
  description: |-
    The commands shown in Example 3 remove fabrikam.com from the list of domains blocked by the current tenant.
    To do this, the first command in the example uses the `New-CsEdgeDomainPattern` cmdlet to create a domain object for fabrikam.com.
    The resulting domain object is then stored in a variable named $x.

    The second command in the example then uses the `Set-CsTenantFederationConfiguration` cmdlet and the Remove method to remove fabrikam.com from the blocked domains list for the specified tenant.
  summary: ""
- title: '-------------------------- Example 4 --------------------------'
  code: |-
    $x = New-CsEdgeDomainPattern -Domain "fabrikam.com"

    Set-CsTenantFederationConfiguration -BlockedDomains @{Add=$x}
  description: |-
    The commands shown in Example 4 add the domain fabrikam.com to the list of domains blocked by the current tenant.
    To add a new blocked domain, the first command in the example uses the `New-CsEdgeDomainPattern` cmdlet to create a domain object for fabrikam.com.
    This object is stored in a variable named $x.

    After the domain object has been created, the second command then uses the `Set-CsTenantFederationConfiguration` cmdlet and the Add method to add fabrikam.com to any domains already on the blocked domains list.
  summary: ""
- title: '-------------------------- Example 5 --------------------------'
  code: |-
    Set-CsTenantFederationConfiguration -BlockedDomains $Null
  description: |-
    Example 5 shows how you can remove all the domains assigned to the blocked domains list for the current tenant.
    To do this, simply include the BlockedDomains parameter and set the parameter value to null ($Null).
    When this command completes, the blocked domain list will be cleared.
  summary: ""
- title: '-------------------------- Example 6 --------------------------'
  code: |-
    $list = New-Object Collections.Generic.List[String]
    $list.add("contoso.com")
    $list.add("fabrikam.com")
    Set-CsTenantFederationConfiguration -AllowedDomainsAsAList $list
  description: |-
    Example 6 shows how you can replace domains in the Allowed Domains using a List collection object.
    First, a List collection is created and domains are added to it, then, simply include the AllowedDomainsAsAList parameter and set the parameter value to the List object.
    When this command completes, the allowed domains list will be replaced with those domains.
  summary: ""
- title: '-------------------------- Example 7 --------------------------'
  code: |-
    $list = New-Object Collections.Generic.List[String]
    $list.add("contoso.com")
    $list.add("fabrikam.com")
    Set-CsTenantFederationConfiguration -AllowedDomainsAsAList @{Add=$list}
  description: |-
    Example 7 shows how you can add domains to the existing Allowed Domains using a List object.
    First, a List is created and domains are added to it, then use the Add method in the AllowedDomainsAsAList parameter to add the domains to the existing allowed domains list. When this command completes, the domains in the list will be added to any domains already on the AllowedDomains list.
  summary: ""
- title: '-------------------------- Example 8 --------------------------'
  code: |-
    $list = New-Object Collections.Generic.List[String]
    $list.add("contoso.com")
    $list.add("fabrikam.com")
    Set-CsTenantFederationConfiguration -AllowedDomainsAsAList @{Remove=$list}
  description: |-
    Example 8 shows how you can remove domains from the existing Allowed Domains using a List object.
    First, a List is created and domains are added to it, then use the Remove method in the AllowedDomainsAsAList parameter to remove the domains from the existing allowed domains list. When this command completes, the domains in the list will be removed from the AllowedDomains list.
  summary: ""
- title: '-------------------------- Example 9 --------------------------'
  code: |-
    Set-CsTenantFederationConfiguration -AllowTeamsConsumer $True -AllowTeamsConsumerInbound $False
  description: |-
    The command shown in Example 9 enables communication with people using Teams with an account that's not managed by an organization, to only be initiated by people in your organization. This means that people using Teams with an account that's not managed by an organization will not be able to discover or start a conversation with people in your organization.
  summary: ""
parameters:
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: AllowedDomains
  description: |+
    Domain objects (created by using the `New-CsEdgeAllowList` cmdlet or the `New-CsEdgeAllowAllKnownDomains` cmdlet) that represent the domains that users are allowed to communicate with.
    If the `New-CsEdgeAllowAllKnownDomains` cmdlet is used then users can communicate with any domain that does not appear on the blocked domains list.
    If the `New-CsEdgeAllowList` cmdlet is used then users can only communicate with domains that have been added to the allowed domains list.

    Note that string values cannot be passed directly to the AllowedDomains parameter.
    Instead, you must create an object reference using the `New-CsEdgeAllowList` cmdlet or the `New-CsEdgeAllowAllKnownDomains` cmdlet and then use the object reference variable as the parameter value.

    The AllowedDomains parameter can support up to 4,000 domains.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Online
  parameterValueGroup: ""
- type: <xref href="List" data-throw-if-not-resolved="False" />
  name: AllowedDomainsAsAList
  description: |+
    You can specify allowed domains using a List object that contains the domains that users are allowed to communicate with. See Examples section.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Online
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: AllowFederatedUsers
  description: |+
    When set to True (the default value) users will be potentially allowed to communicate with users from other domains.
    If this property is set to False then users cannot communicate with users from other domains regardless of the values assigned to the AllowedDomains and BlockedDomains properties.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Online
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: AllowPublicUsers
  description: |+
    When set to True (the default value) users will be potentially allowed to communicate with users who have accounts on public IM and presence providers such as Windows Live, Yahoo, and AOL.
    The collection of public providers that users can actually communicate with is managed by using the `Set-CsTenantPublicProvider` cmdlet.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Online
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: AllowTeamsConsumer
  description: |+
    Allows federation with people using Teams with an account that's not managed by an organization.

  defaultValue: "True"
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: AllowTeamsConsumerInbound
  description: |+
    Allows people using Teams with an account that's not managed by an organization, to discover and start communication with users in your organization. When -AllowTeamsConsumer is enabled and this parameter is disabled, only the users in your organization will be able to discover and start communication with people using Teams with an account that's not managed by an organization, but they will not discover and start communications with users in your organization.

  defaultValue: "True"
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="List" data-throw-if-not-resolved="False" />
  name: BlockedDomains
  description: |+
    If the AllowedDomains property has been set to AllowAllKnownDomains, then users will be allowed to communicate with users from any domain except domains that appear in the blocked domains list.
    If the AllowedDomains property has not been set to AllowAllKnownDomains, then the blocked list is ignored, and users can only communicate with domains that have been expressly added to the allowed domains list.
    The BlockedDomains parameter can support up to 4,000 domains.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Online
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - Skype for Business Online
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Suppresses the display of any non-fatal error message that might arise when running the command.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Online
  parameterValueGroup: ""
- type: <xref href="XdsIdentity" data-throw-if-not-resolved="False" />
  name: Identity
  description: |+
    Specifies the collection of tenant federation configuration settings to be modified.
    Because each tenant is limited to a single, global collection of federation settings there is no need include this parameter when calling the `Set-CsTenantFederationConfiguration` cmdlet.
    If you do choose to use the Identity parameter you must also include the Tenant parameter.
    For example:

    `Set-CsTenantFederationConfiguration -Tenant "bf19b7db-6960-41e5-a139-2aa373474354" -Identity "global"`

  defaultValue: None
  position: "2"
  aliases: ""
  applicable:
  - Skype for Business Online
  parameterValueGroup: ""
- type: <xref href="PSObject" data-throw-if-not-resolved="False" />
  name: Instance
  description: |+
    Allows you to pass a reference to an object to the cmdlet rather than set individual parameter values.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Online
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: SharedSipAddressSpace
  description: |+
    When set to True, indicates that the users homed on Skype for Business Online use the same SIP domain as users homed on the on-premises version of Skype for Business Server.
    The default value is False, meaning that the two sets of users have different SIP domains.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Online
  parameterValueGroup: ""
- type: <xref href="Guid" data-throw-if-not-resolved="False" />
  name: Tenant
  description: |+
    Globally unique identifier (GUID) of the tenant account whose federation settings are being modified.
    For example:

    `-Tenant "38aad667-af54-4397-aaa7-e94c79ec2308"`

    You can return your tenant ID by running this command:

    `Get-CsTenant | Select-Object DisplayName, TenantID`

    If you are using a remote session of Windows PowerShell and are connected only to Skype for Business Online you do not have to include the Tenant parameter.
    Instead, the tenant ID will automatically be filled in for you based on your connection information.
    The Tenant parameter is primarily for use in a hybrid deployment.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Online
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: TreatDiscoveredPartnersAsUnverified
  description: |+
    When set to True, messages sent from discovered partners are considered unverified.
    That means that those messages will be delivered only if they were sent from a person who is on the recipient's Contacts list.
    The default value is False ($False).

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Skype for Business Online
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Describes what would happen if you executed the command without actually executing the command.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - Skype for Business Online
  parameterValueGroup: ""
applicable:
- Skype for Business Online
uid: SkypeForBusiness.Set-CsTenantFederationConfiguration
name: Set-CsTenantFederationConfiguration
description: |-
  Federation is a service that enables users to exchange IM and presence information with users from other domains.
  With Skype for Business Online, administrators can use the federation configuration settings to govern:

  Whether or not users can communicate with people from other domains and if so, which domains they are allowed to communicate with.

  Whether or not users can communicate with people who have accounts on public IM and presence providers such as Windows Live, Skype, or people using Microsoft Teams with an account that's not managed by an organization.

  Administrators can use the `Set-CsTenantFederationConfiguration` cmdlet to enable and disable federation with other domains and federation with public providers.
  In addition, this cmdlet can be used to expressly indicate the domains that users can communicate with and/or the domains that users are not allowed to communicate with.
  However, administrators must use the `Set-CsTenantPublicProvider` cmdlet in order to indicate the public IM and presence providers that users can and cannot communicate with.
metadata:
  external help file: Microsoft.Rtc.Management.Hosted.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/set-cstenantfederationconfiguration
  applicable: Skype for Business Online
  title: Set-CsTenantFederationConfiguration
  schema: 2.0.0
  manager: bulenteg
  author: tomkau
  ms.author: tomkau
  ms.reviewer: ""
