### YamlMime:PowershellCmdlet
summary: |-
  Modifies Skype for Business Server properties for an existing hybrid application endpoint.

  This cmdlet was introduced in the July 2017 cumulative update for the Lync Server 2013 and May 2017 cumulative update for Skype Business Server 2015.
module: SkypeForBusiness
notes: ""
inputs:
- name: <xref href="Microsoft.Rtc.Management.AD.UserIdParameter" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="System.Object" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: New-CsHybridApplicationEndpoint
  href: https://learn.microsoft.com/powershell/module/skype/new-cshybridapplicationendpoint?view=skype-ps
- text: Get-CsHybridApplicationEndpoint
  href: https://learn.microsoft.com/powershell/module/skype/get-cshybridapplicationendpoint?view=skype-ps
- text: Remove-CsHybridApplicationEndpoint
  href: https://learn.microsoft.com/powershell/module/skype/remove-cshybridapplicationendpoint?view=skype-ps
syntaxes:
- Set-CsHybridApplicationEndpoint [-Identity] <HybridApplicationEndpointIdParameter> [-DisplayName <String>] [-LineUri <String>] [-DomainController <Fqdn>] [-PassThru] [-WhatIf] [-Confirm] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 --------------------------'
  code: |-
    PS C:\> Set-CsHybridApplicationEndpoint -Identity "CN={4f6c99fe-7999-4088-ac4d-e88e0b3d3820},OU=Redmond,DC=litwareinc,DC=com" -DisplayName HybridAppEndpoint1 -LineURI tel:+14255550100
  description: |-
    This example modify the DisplayName and LineURI attributes for the specified hybrid application endpoint.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: DisplayName
  description: |+
    Friendly name for the application endpoint that is being modified.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="Fqdn" data-throw-if-not-resolved="False" />
  name: DomainController
  description: |+
    Enables you to connect to the specified domain controller in order to retrieve user information. To connect to a particular domain controller, include the DomainController parameter followed by the fully qualified domain name (FQDN) (for example, atl-cs-001.litwareinc.com).

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="UserIdParameter" data-throw-if-not-resolved="False" />
  name: Identity
  isRequired: true
  description: |+
    The ApplicationId or Client Id for which the endpoint that is being modified.

  defaultValue: None
  pipelineInput: true
  position: "0"
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: LineUri
  description: |+
    Valid phone number for the application endpoint that is being modified. (Not currently supported through BOT framework)

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: PassThru
  description: |+
    Returns an object representing the item with which you are working. By default, this cmdlet does not generate any output.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs. The cmdlet is not run.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - Lync Server 2013
  - Skype for Business Server 2015
  - Skype for Business Server 2019
  parameterValueGroup: ""
applicable:
- Lync Server 2013
- Skype for Business Server 2015
- Skype for Business Server 2019
uid: SkypeForBusiness.Set-CsHybridApplicationEndpoint
name: Set-CsHybridApplicationEndpoint
description: |-
  The `Set-CsHybridApplicationEndpoint` cmdlet enables you to modify the Skype for Business Server related hybrid application endpoint attributes that are stored in Active Directory Domain Services. For example, you can modify an endpoint's line URI number; or modify an endpoint's display name.
metadata:
  external help file: Microsoft.Rtc.Management.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/skype/set-cshybridapplicationendpoint
  applicable: Lync Server 2013, Skype for Business Server 2015, Skype for Business Server 2019
  title: Set-CsHybridApplicationEndpoint
  schema: 2.0.0
  manager: rogupta
  author: hirenshah1
  ms.author: hirshah
  ms.reviewer: ""
