### YamlMime:PowershellCmdlet
summary: |-
  Get application instance for the tenant from Microsoft Entra ID.
module: MicrosoftTeamsPowerShell
notes: ""
links:
- text: Set-CsOnlineApplicationInstance
  href: Set-CsOnlineApplicationInstance.yml
- text: New-CsOnlineApplicationInstance
  href: New-CsOnlineApplicationInstance.yml
- text: Find-CsOnlineApplicationInstance
  href: Find-CsOnlineApplicationInstance.yml
- text: Sync-CsOnlineApplicationInstance
  href: Sync-CsOnlineApplicationInstance.yml
syntaxes:
- Get-CsOnlineApplicationInstance [[-Identity] <string>] [[-Identities] <string>] [[-ResultSize] <int>] [[-Skip] <int>] [-Force] [-WhatIf] [-Confirm] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 --------------------------'
  code: |-
    Get-CsOnlineApplicationInstance -Identity appinstance01@contoso.com
  description: |-
    This example returns the application instance with identity "appinstance01@contoso.com".
  summary: ""
- title: '-------------------------- Example 2 --------------------------'
  code: |-
    Get-CsOnlineApplicationInstance -Identities appinstance01@contoso.com,appinstance02@contoso.com
  description: |-
    This example returns the application instance with identities "appinstance01@contoso.com" and "appinstance02@contoso.com". Query with multiple comma separated Identity.
  summary: ""
- title: '-------------------------- Example 3 --------------------------'
  code: |-
    Get-CsOnlineApplicationInstance -ResultSize 10
  description: |-
    This example returns the first 10 application instances.
  summary: ""
- title: '-------------------------- Example 4 --------------------------'
  code: |-
    Get-CsOnlineApplicationInstance
  description: |-
    This example returns the details of all application instances.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: "False"
  position: Named
  aliases: cf
  applicable:
  - Microsoft Teams
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    This switch specifies whether to suppress warning and confirmation messages. It can be useful in scripting to suppress interactive prompts. If it isn't provided in the command, you're prompted for administrative input if required.

  defaultValue: "False"
  position: Named
  aliases: ""
  applicable:
  - Microsoft Teams
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Identities
  description: |+
    The UPNs or the object IDs of the application instances to retrieve, separated with comma. If this parameter nor parameter Identity are not provided, it will retrieve all application instances in the tenant.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Microsoft Teams
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Identity
  description: |+
    The UPN or the object ID of the application instance to retrieve. If this parameter nor parameter Identities are not provided, it will retrieve all application instances in the tenant.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Microsoft Teams
  parameterValueGroup: ""
- type: <xref href="System.Int32" data-throw-if-not-resolved="False" />
  name: ResultSize
  description: |+
    The result size for bulk get. This parameter is currently not working.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Microsoft Teams
  parameterValueGroup: ""
- type: <xref href="System.Int32" data-throw-if-not-resolved="False" />
  name: Skip
  description: |+
    Skips the first specified number of returned results. The default value is 0. This parameter is currently not working.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Microsoft Teams
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: "False"
  position: Named
  aliases: wi
  applicable:
  - Microsoft Teams
  parameterValueGroup: ""
applicable:
- Microsoft Teams
uid: MicrosoftTeamsPowerShell.Get-CsOnlineApplicationInstance
name: Get-CsOnlineApplicationInstance
description: |-
  This cmdlet is used to get details of an application instance.
metadata:
  external help file: Microsoft.Rtc.Management.Hosted.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/teams/get-csonlineapplicationinstance
  applicable: Microsoft Teams
  title: Get-CsOnlineApplicationInstance
  schema: 2.0.0
  manager: bulenteg
  author: jenstrier
  ms.author: serdars
  ms.reviewer: ""
