### YamlMime:PowershellCmdlet
summary: |-
  Use the Set-CsOnlineVoicemailUserSettings cmdlet to modify the online voicemail user settings of a specific user.
  New online voicemail user settings of the user would be returned after executing.
module: MicrosoftTeamsPowerShell
notes: ""
inputs:
- name: <xref href="None" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Rtc.Management.Hosted.Voicemail.Models.VoicemailUserSettings" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Get-CsOnlineVoicemailUserSettings
  href: Get-CsOnlineVoicemailUserSettings.yml
syntaxes:
- >-
  Set-CsOnlineVoicemailUserSettings [-Identity] <string> [-CallAnswerRule <Object>] [-DefaultGreetingPromptOverwrite <string>]

  [-DefaultOofGreetingPromptOverwrite <string>] [-Force] [-OofGreetingEnabled <boolean>] [-OofGreetingFollowAutomaticRepliesEnabled <boolean>]

  [-OofGreetingFollowCalendarEnabled <boolean>] [-PromptLanguage <string>] [-ShareData <boolean>] [-TransferTarget <string>]

  [-VoicemailEnabled <boolean>] [-WhatIf] [-Confirm] [<CommonParameters>]
examples:
- title: '-------------------------- Example 1 --------------------------'
  code: |-
    Set-CsOnlineVoicemailUserSettings -Identity sip:user1@contoso.com -VoicemailEnabled $true
  description: |-
    This example changes VoicemailEnabled setting to true for the user with SIP URI sip:user1@contoso.com.
  summary: ""
- title: '-------------------------- Example 2 --------------------------'
  code: |-
    Set-CsOnlineVoicemailUserSettings -Identity user2@contoso.com -PromptLanguage "en-US" -OofGreetingFollowCalendarEnabled $false
  description: |-
    This example changes PromptLanguage setting to "en-US" and OofGreetingFollowCalendarEnabled setting to false for user2@contoso.com.
  summary: ""
- title: '-------------------------- Example 3 --------------------------'
  code: |-
    Set-CsOnlineVoicemailUserSettings -Identity user3@contoso.com -CallAnswerRule PromptOnlyWithTransfer -TransferTarget sip:user4@contoso.com
  description: |-
    This example changes CallAnswerRule setting to PromptOnlyWithTransfer and set TransferTarget to "sip:user4@contoso.com" for user3@contoso.com.
  summary: ""
- title: '-------------------------- Example 4 --------------------------'
  code: |-
    Set-CsOnlineVoicemailUserSettings -Identity user5@contoso.com -CallAnswerRule VoicemailWithTransferOption -TransferTarget "+14255551234"
  description: |-
    This example changes CallAnswerRule setting to VoicemailWithTransferOption and set TransferTarget to "+14255551234" for user5@contoso.com..
  summary: ""
- title: '-------------------------- Example 5 --------------------------'
  code: |-
    Set-CsOnlineVoicemailUserSettings -Identity user6@contoso.com -DefaultGreetingPromptOverwrite "Hi, I am currently not available."
  description: |-
    This example changes DefaultGreetingPromptOverwrite setting to "Hi, I am currently not available." for user6@contoso.com.
  summary: ""
parameters:
- type: <xref href="Object" data-throw-if-not-resolved="False" />
  name: CallAnswerRule
  description: |+
    The CallAnswerRule parameter represents the value of the call answer rule, which can be any of the following:

    - DeclineCall
    - PromptOnly
    - PromptOnlyWithTransfer
    - RegularVoicemail
    - VoicemailWithTransferOption

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Microsoft Teams
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before executing the command.

  defaultValue: None
  position: Named
  aliases: cf
  applicable:
  - Microsoft Teams
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: DefaultGreetingPromptOverwrite
  description: |+
    The DefaultGreetingPromptOverwrite parameter represents the contents that overwrite the default normal greeting prompt.
    If the user's normal custom greeting is not set and DefaultGreetingPromptOverwrite is not empty, the voicemail service will play this overwrite greeting instead of the default normal greeting in the voicemail deposit scenario.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Microsoft Teams
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: DefaultOofGreetingPromptOverwrite
  description: |+
    The DefaultOofGreetingPromptOverwrite parameter represents the contents that overwrite the default out-of-office greeting prompt.
    If the user's out-of-office custom greeting is not set and DefaultOofGreetingPromptOverwrite is not empty, the voicemail service will play this overwrite greeting instead of the default out-of-office greeting in the voicemail deposit scenario.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Microsoft Teams
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Specifies whether to suppress warning and confirmation messages. It can be useful in scripting to suppress interactive prompts. If the Force switch isn't provided in the command, you're prompted for administrative input if required.

  defaultValue: "False"
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: Identity
  isRequired: true
  description: |+
    The Identity parameter represents the ID of the specific user in your organization; this can be either a SIP URI or an Object ID.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Microsoft Teams
  parameterValueGroup: ""
- type: <xref href="System.Boolean" data-throw-if-not-resolved="False" />
  name: OofGreetingEnabled
  description: |+
    The OofGreetingEnabled parameter represents whether to play out-of-office greeting in voicemail deposit scenario.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Microsoft Teams
  parameterValueGroup: ""
- type: <xref href="System.Boolean" data-throw-if-not-resolved="False" />
  name: OofGreetingFollowAutomaticRepliesEnabled
  description: |+
    The OofGreetingFollowAutomaticRepliesEnabled parameter represents whether to play out-of-office greeting in voicemail deposit scenario when user set automatic replies in Outlook.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Microsoft Teams
  parameterValueGroup: ""
- type: <xref href="System.Boolean" data-throw-if-not-resolved="False" />
  name: OofGreetingFollowCalendarEnabled
  description: |+
    The OofGreetingFollowCalendarEnabled parameter represents whether to play out-of-office greeting in voicemail deposit scenario when user set out-of-office in calendar.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Microsoft Teams
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: PromptLanguage
  description: |+
    The PromptLanguage parameter represents the language that is used to play voicemail prompts. 

    The following languages are supported:

    - "ar-EG" (Arabic - Egypt)
    - "ar-SA" (Arabic - Saudi Arabia)
    - "bg-BG" (Bulgarian - Bulgaria)
    - "ca-ES" (Catalan - Catalan)
    - "cy-GB" (Welsh - United Kingdom)
    - "cs-CZ" (Czech - Czech Republic)
    - "da-DK" (Danish - Denmark)
    - "de-AT" (German - Austria)
    - "de-CH" (German - Switzerland)
    - "de-DE" (German - Germany)
    - "el-GR" (Greek - Greece)
    - "en-AU" (English - Australia)
    - "en-CA" (English - Canada)
    - "en-GB" (English - United Kingdom)
    - "en-IE" (English - Ireland)
    - "en-IN" (English - India)
    - "en-PH" (English - Philippines)
    - "en-US" (English - United States)
    - "en-ZA" (English - South Africa)
    - "es-ES" (Spanish - Spain)
    - "es-MX" (Spanish - Mexico)
    - "et-EE" (Estonian - Estonia)
    - "fi-FI" (Finnish - Finland)
    - "fr-BE" (French - Belgium)
    - "fr-CA" (French - Canada)
    - "fr-CH" (French - Switzerland)
    - "fr-FR" (French - France)
    - "he-IL" (Hebrew - Israel)
    - "hi-IN" (Hindi - India)
    - "hr-HR" (Croatian - Croatia)
    - "hu-HU" (Hungarian - Hungary)
    - "id-ID" (Indonesian - Indonesia)
    - "it-IT" (Italian - Italy)
    - "ja-JP" (Japanese - Japan)
    - "ko-KR" (Korean - Korea)
    - "lt-LT" (Lithuanian - Lithuania)
    - "lv-LV" (Latvian - Latvia)
    - "nl-BE" (Dutch - Belgium)
    - "nl-NL" (Dutch - Netherlands)
    - "nb-NO" (Norwegian, Bokm√•l - Norway)
    - "pl-PL" (Polish - Poland)
    - "pt-BR" (Portuguese - Brazil)
    - "pt-PT" (Portuguese - Portugal)
    - "ro-RO" (Romanian - Romania)
    - "ru-RU" (Russian - Russia)
    - "sk-SK" (Slovak - Slovakia)
    - "sl-SI" (Slovenian - Slovenia)
    - "sv-SE" (Swedish - Sweden)
    - "th-TH" (Thai - Thailand)
    - "tr-TR" (Turkish - Turkey)
    - "vi-VN" (Vietnamese - Viet Nam)
    - "zh-CN" (Chinese - Simplified, PRC)
    - "zh-TW" (Chinese - Traditional, Taiwan)
    - "zh-HK" (Chinese - Traditional, Hong Kong S.A.R.)

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Microsoft Teams
  parameterValueGroup: ""
- type: <xref href="System.Boolean" data-throw-if-not-resolved="False" />
  name: ShareData
  description: |+
    Specifies whether voicemail and transcription data is shared with the service for training and improving accuracy.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Microsoft Teams
  parameterValueGroup: ""
- type: <xref href="System.String" data-throw-if-not-resolved="False" />
  name: TransferTarget
  description: |+
    The TransferTarget parameter represents the target to transfer the call when call answer rule set to PromptOnlyWithTransfer or VoicemailWithTransferOption.
    Value of this parameter should be a SIP URI of another user in your organization. 
    For user with Enterprise Voice enabled, a valid telephone number could also be accepted as TransferTarget.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Microsoft Teams
  parameterValueGroup: ""
- type: <xref href="System.Boolean" data-throw-if-not-resolved="False" />
  name: VoicemailEnabled
  description: |+
    The VoicemailEnabled parameter represents whether to enable voicemail service. If set to $false, the user has no voicemail service.

  defaultValue: None
  position: Named
  aliases: ""
  applicable:
  - Microsoft Teams
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Describes what would happen if you executed the command without actually executing the command.

  defaultValue: None
  position: Named
  aliases: wi
  applicable:
  - Microsoft Teams
  parameterValueGroup: ""
applicable:
- Microsoft Teams
uid: MicrosoftTeamsPowerShell.Set-CsOnlineVoicemailUserSettings
name: Set-CsOnlineVoicemailUserSettings
description: |-
  The Set-CsOnlineVoicemailUserSettings cmdlet lets tenant admin modify the online voicemail user settings of a specific user in the organization. New online voicemail user settings of the user would be returned after executing.
  For example, tenant admin could enable/disable voicemail, change voicemail prompt language, modify out-of-office voicemail greeting settings, or setup simple call answer rules. Only those properties that tenant admin have actually provided with be modified. If an online voicemail user setting was not set by tenant admin, it would remain the old value after this cmdlet has been executed.
metadata:
  external help file: Microsoft.Rtc.Management.Hosted.dll-help.xml
  online version: https://learn.microsoft.com/powershell/module/teams/set-csonlinevoicemailusersettings
  applicable: Microsoft Teams
  title: Set-CsOnlineVoicemailUserSettings
  schema: 2.0.0
  manager: bulenteg
  author: jenstrier
  ms.author: serdars
  ms.reviewer: ""
